#!/bin/sh
#
# $Id: mingw-cross,v 1.2 2004-01-15 02:03:53 uid66849 Exp $
#

[ -r VERSION ] || exit 1

VERSION=`cat VERSION`
BUILD_ROOT=/tmp/gnokii-$VERSION-win32-build
ZIPFILE=`pwd`/gnokii-$VERSION-win32.zip

rm -r $BUILD_ROOT
win32/mingw-cross/mingw-cross.sh

make DESTDIR=$BUILD_ROOT install

mv $BUILD_ROOT/lib/gnokii.dll $BUILD_ROOT/bin/

install COPYRIGHT $BUILD_ROOT
install COPYING $BUILD_ROOT
make DESTDIR=$BUILD_ROOT docdir=/doc -C Docs install

cd $BUILD_ROOT
zip -r "$ZIPFILE" .
